apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demonamespace2
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: demonamespace2
subsets:
- addresses:
  - ip: 192.168.3.130
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
